# sheet 1
COL_DATE = 'A'
COL_ID = 'B'
COL_PASSWORD = 'C'
COL_PROFILE_ID = 'D'
COL_NAME = 'E'
COL_BIRTHDAY = 'F'
COL_SEX = 'G'
COL_2FA = 'J'
COL_FACEBOOK = 'K'
COL_STATUS = 'N'
COL_EMAIL_STATUS = 'O'

# sheet proxy
COL_PROXY = 'A'
COL_IP = 'B'
COL_PROXY_STATUS = 'C'
